version: '3'
volumes:
  nextcloud:
  db:

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
       - db:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: samir
        MYSQL_PASSWORD: redhat
        MYSQL_DATABASE: nextcloud
        MYSQL_USER: samir
    

  app:
    image: nextcloud:17-apache
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
    
  

   